name: CI Pipeline

on:
  workflow_call:

jobs:
##################################
# Build
##################################
  testingTemplate:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/test-template.yml

# ##################################
# # Testing
# ##################################

#   testing:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Test Step
#         run: echo "Running tests..."
#       - script: |
#           echo "Hello World!"

# ##################################
# # Deploy
# ##################################
#   deploy:
#     runs-on: ubuntu-latest
#     needs: testing
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Deploy Step
#         run: echo "Deploying the application..."