name: Test template

on:
  workflow_call:


jobs:
  printPython:
    runs-on: ubuntu-latest
    steps:
      - script: |
          echo "This is a test template for printing Python version"
          python --version